### ISSUE TITLE
🐕

### ISSUE THREAD

**Issue by cyltt6** [AlexTan-b-z/JavaWebTCPBookMangeSystem#3]
为啥不上传数据库是因为copy别人的吗

**Comment by 15573255668** [comment]
？



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 16, 2024 16:54 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [AlexTan-b-z/JavaWebTCPBookMangeSystem] 🐕 (Issue #3)




 
为啥不上传数据库是因为copy别人的吗

**Comment by AlexTan-b-z** [comment]
这年头，伸手党还有理了，爱用用，不用gun
